/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   payload__init
                     (Payload         *message)
{
  static const Payload init_value = PAYLOAD__INIT;
  *message = init_value;
}
size_t payload__get_packed_size
                     (const Payload *message)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t payload__pack
                     (const Payload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t payload__pack_to_buffer
                     (const Payload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Payload *
       payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Payload *)
     protobuf_c_message_unpack (&payload__descriptor,
                                allocator, len, data);
}
void   payload__free_unpacked
                     (Payload *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor payload__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Payload, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Payload, data),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned payload__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Payload",
  "Payload",
  "Payload",
  "",
  sizeof(Payload),
  2,
  payload__field_descriptors,
  payload__field_indices_by_name,
  1,  payload__number_ranges,
  (ProtobufCMessageInit) payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
